# Generated by Django 2.2.1 on 2019-05-14 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.FloatField(blank=True, default='')),
                ('answer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='earned_points', to='answers.Answer')),
                ('who_gives_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_answers', to='teachers.Teacher')),
            ],
        ),
    ]
