# Generated by Django 2.2.1 on 2019-05-14 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('exams', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.FloatField(default='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='exams.Exam')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='teachers.Teacher')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='students.Student')),
            ],
        ),
    ]
